### ISSUE TITLE
Type or namespace Ical could not be found

### ISSUE THREAD

**Issue by salmankhann** [ical-org/ical.net#101] opened 2016-08-19 07:52 UTC
I've followed your tutorial on the wiki and the following namespaces are not found
using Ical.Net;
using Ical.Net.DataTypes;
using Ical.Net.Serialization.iCalendar.Serializers;

I'm using version 2.2.6. 

How can I fix this?

**Comment by rianjs** [comment] 2016-08-19 10:41
Please post your complete source code

**Comment by salmankhann** [comment] 2016-08-19 10:54
```
        Ical.Net.Event eventToCreate = new Ical.Net.Event()
        {
            Summary = eventFromDB.title,
            Description = eventFromDB.detail,
            DtStart = new CalDateTime(eventFromDB.finalizedVotingOption.startDate),
            DtEnd = new CalDateTime(eventFromDB.finalizedVotingOption.startDate.AddMinutes((double)eventFromDB.duration)),
            Location = eventFromDB.finalizedVotingOption.location.title,
            Organizer = new Organizer(eventFromDB.organizer.name)

        };
        Calendar calendar = new Calendar();
        calendar.Events.Add(eventToCreate);

        CalendarSerializer serializer = new CalendarSerializer(calendar);
        string calendarStringToReturn = serializer.SerializeToString();
```

My solution is not recognizing any of the ICal.*\* libraries. I'm using it in an ASP.NET MVC application. Any ideas?

**Comment by rianjs** [comment] 2016-08-19 11:04
You added the library as a reference to your csproj?

**Comment by salmankhann** [comment] 2016-08-19 11:05
No I got it from NuGet. I also tried downloading the source and compiling but it has syntax errors

**Comment by rianjs** [comment] 2016-08-19 19:01
It sounds like you're new to Visual Studio and nuget. This link should get you started:
http://www.codeproject.com/Tips/990440/How-to-Use-NuGet-Packages

The errors you're seeing aren't specific to ical.net. They're normal reference-can't-be-found errors.

**Comment by salmankhann** [comment] 2016-08-19 19:03
@rianjs I'm not new to the VS; i've been coding on it for around 5 years now. My project has other dependencies from Nuget, but its just not able to find Ical.net for some reason

**Comment by kdaveid** [comment] 2016-08-19 22:17
Hi there
- Which nuget feed do you use? 
- Which project type? (csproj or xproj)

I recommend this feed: https://api.nuget.org/v3/index.json. On VS-level and on project level there can be different sources defined. Do you use the nuget-Browser in VS or via project.json?

**Comment by xrisdoc** [comment] 2016-08-22 10:00
Hello,

I too am experiencing this same issue/errors. I installed this via NuGet too (version 2.2.6) and I have included the following using statements:

```
using Ical.Net;
using Ical.Net.DataTypes;
using Ical.Net.Serialization.iCalendar.Serializers;
```

All of the relevant references to the assemblies are present within the project (i.e. Ical.Net and Ical.Net.Collections etc.), which were added by the NuGet Package itself.

All of the intellisense for the relevant types within the ICal.Net assemblies does seem to be working as it should. So, it is referencing them in some way, otherwise we would not be getting any of the intellisense. It is only when it comes to actually building the project that these errors start to appear.

Thanks,
Chris

**Comment by xrisdoc** [comment] 2016-08-22 10:22
Hello,

I have just discovered that this was due to my project target framework being set to version 4.5.

It seems the Ical.Net assemblies were built against the version 4.5.2 framework, which seems to have caused the issue. 

I have now set the target framework of my project to version 4.5.2 and it seems to be building OK now.

I'll just need to ensure that all of my other projects are built using version 4.5.2 too now. Hopefully, this won't cause any further issues.

Thanks,
Chris

**Comment by kdaveid** [comment] 2016-08-22 10:47
Thanks Chris. I can confirm the build error on .Net 4.5 with my sample app. If you look at the build settings in the [project file](https://github.com/rianjs/ical.net/blob/master/ical.NET/ical.NET.csproj#L29-L31) you see it's being build against 4.5.2.

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release45|AnyCPU'">
  <OutputPath>bin\Release\net45\</OutputPath>
  <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
  <DefineConstants>TRACE</DefineConstants>
  <DocumentationFile>bin\Release\net45\Ical.Net.xml</DocumentationFile>
  <Optimize>true</Optimize>
  <DebugType>pdbonly</DebugType>
  <PlatformTarget>AnyCPU</PlatformTarget>
  <ErrorReport>prompt</ErrorReport>
  <NoWarn>CS7035</NoWarn>
</PropertyGroup>
```

After a quick test to build against .net 4.5 I can tell you it compiles well and all tests are passing. I prepared a nuget package for you to consume. So let me know.

I'm not sure if we really need a build against 4.5 on a regular Basis. 4.5.2 should work. If you can live with 4.5.2 I'd rather like to not change the build system.

**Comment by xrisdoc** [comment] 2016-08-22 11:29
Hello,

Thanks for that, but I think I am OK for now!

I have now set the target framework to 4.5.2 on all of the relevant projects in my solution and it seems to be OK so far. So, i'm happy to stick with the version built against version 4.5.2 for now.

If it turns out that I do in fact need this specifically for version 4.5, then I can just clone the repo and build it against version 4.5 myself.

Thanks,
Chris

**Comment by kdaveid** [comment] 2016-08-22 11:39
@salmankhann This i probably the same case with you. Can you confirm that we can close the issue?

**Comment by salmankhann** [comment] 2016-08-22 17:55
@kdaveid any specific reason for targeting the .2 release ? If you don't have any specific dependencies on .2 then it's better to target 4.5 as it opens your framework up for a broader adoption

**Comment by rianjs** [comment] 2016-08-22 19:09
I'm open to targeting 4.5, but since MS has 4.5.2 as a side-by-side install next to 4.5, I would rather have this be an additive change. That is, publish a 4.5 version in addition to keeping the 4.5.2 version.

## 

A little more detail

I generally view point releases as being "safer" targets than their predecessors. For example, .NET 4.6 was a bad release because of [a tail call recursion bug](https://blogs.msdn.microsoft.com/dotnet/2015/07/28/ryujit-bug-advisory-in-the-net-framework-4-6/). 4.6.1 (released very quickly after) fixed this bug. In the case of 4.6, MS didn't expose the ability to target specific 4.6 point releases: we can only target 4.6 as a TFM, which (I assume) means it's targeting 4.6.\* behind the scenes. Maybe it's possible to contort the installed framework versions and developer packs so you _can_ target specific point releases ([the nuget docs imply this is so](https://docs.nuget.org/create/targetframeworks#supported-frameworks)) but I tried targeting 4.6.1 specifically in the `csproj` files a few weeks ago, and it didn't work. I didn't pursue it further.

I would guess that specifying 4.6 will produce assemblies that do sensible things when MS decides to have a .NET version that's side-by-side-with-the-old vs replaces-the-old.

**Comment by kdaveid** [comment] 2016-08-23 05:30
@salmankhann I don't see any reason - but I agree with @rianjs with "safer" targets. 
A quick glance on [the diffs between the versions](http://firstfloorsoftware.com/labs/difflists) we're probably ok just to target blindly v4.5 - in this case.

**Comment by salmankhann** [comment] 2016-08-23 14:21
I see the point behind safer targets; but semantically speaking, targeting a particular release sends a message that your framework uses features or capabilities provided by that specific release which does not seem to be the case from our discussion. 

Choosing point releases should be the decision of the person using the framework as opposed to being forced into unless ofc the framework author has a strong reason to deviate from the norm which does not seem the case here.

What do you think?

**Comment by rianjs** [comment] 2016-08-23 17:28
e6397821a3626fbb51452beee0291bee9be7b201

**Comment by rianjs** [comment] 2016-08-23 17:28
Nuget package version 2.2.7 (which should be indexed in the next few minutes) targets 4.5 instead of 4.5.2.

https://www.nuget.org/packages/Ical.Net

**Closed as completed by rianjs** 2016-08-23 17:28 UTC
