### ISSUE TITLE
One or more packages are incompatible with .NETCoreApp Version=v1.0

### ISSUE THREAD

**Issue by chrisjmccrum** [ical-org/ical.net#83] opened 2016-07-29 15:57 UTC
Will there be support for netcoreapp1.0 in the near future? Temporarily I can target net46 but unfortunately that isn't a great long term solution for us.

**Comment by rianjs** [comment] 2016-08-17 19:07
Going to close this as a duplicate of #23

**Closed as completed by rianjs** 2016-08-17 19:07 UTC
Labels: duplicate
