### ISSUE TITLE
The time zone offset must be within plus or minus 14 hours.

### ISSUE THREAD

**Issue by GrumpyMeow** [ical-org/ical.net#147] opened 2016-09-29 14:21 UTC
I receive this error upon loading a public calendar from icloud.

I've posted some parts of the raw data which have exceptional TZOFFSETTO values. Hopefully this helps in resolving the issue:

```
BEGIN:VTIMEZONE
TZID:Europe/Brussels
X-LIC-LOCATION:Europe/Brussels
BEGIN:STANDARD
DTSTART:18800101T000000
RDATE;VALUE=DATE-TIME:18800101T000000
TZNAME:BMT
TZOFFSETFROM:+1730
TZOFFSETTO:+1730
END:STANDARD
```

```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:STANDARD
DTSTART:18930401T000000
RDATE;VALUE=DATE-TIME:18930401T000000
TZNAME:CEST
TZOFFSETFROM:+5328
TZOFFSETTO:+0100
END:STANDARD
```

```
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
X-LIC-LOCATION:Europe/Amsterdam

BEGIN:STANDARD
DTSTART:18350101T000000
RDATE;VALUE=DATE-TIME:18350101T000000
TZNAME:S
TZOFFSETFROM:+1932
TZOFFSETTO:+1932
END:STANDARD

BEGIN:DAYLIGHT
DTSTART:19160501T000000
RDATE;VALUE=DATE-TIME:19160501T000000
RDATE;VALUE=DATE-TIME:19170416T020000
RDATE;VALUE=DATE-TIME:19220326T020000
RDATE;VALUE=DATE-TIME:19230601T020000
RDATE;VALUE=DATE-TIME:19240330T020000
RDATE;VALUE=DATE-TIME:19250605T020000
RDATE;VALUE=DATE-TIME:19320522T020000
RDATE;VALUE=DATE-TIME:19370522T020000
TZNAME:NST
TZOFFSETFROM:+1932
TZOFFSETTO:+011932
END:DAYLIGHT
```

Stacktrace:
System.FormatException was unhandled
  HResult=-2146233033
  Message=The time zone offset must be within plus or minus 14 hours.
  Source=mscorlib
  StackTrace:
       at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
       at System.DateTimeOffset.Parse(String input)
       at Ical.Net.Serialization.iCalendar.Serializers.DataTypes.UtcOffsetSerializer.GetOffset(String rawOffset) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\Serializers\DataTypes\UTCOffsetSerializer.cs:line 42
       at Ical.Net.DataTypes.UtcOffset..ctor(String value) in C:\dev\ical.net\ical.NET\DataTypes\UTCOffset.cs:line 26
       at Ical.Net.Serialization.iCalendar.Serializers.DataTypes.UtcOffsetSerializer.Deserialize(TextReader tr) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\Serializers\DataTypes\UTCOffsetSerializer.cs:line 32
       at Ical.Net.Serialization.iCalendar.Serializers.DataMapSerializer.Deserialize(TextReader tr) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\Serializers\DataMapSerializer.cs:line 56
       at Ical.Net.Serialization.iCalendar.iCalParser.property(ISerializationContext ctx, ICalendarPropertyListContainer c) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\iCalParser.cs:line 292
       at Ical.Net.Serialization.iCalendar.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\iCalParser.cs:line 415
       at Ical.Net.Serialization.iCalendar.iCalParser.component(ISerializationContext ctx, ISerializerFactory sf, ICalendarComponentFactory cf, ICalendarObject o) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\iCalParser.cs:line 420
       at Ical.Net.Serialization.iCalendar.iCalParser.icalbody(ISerializationContext ctx, ICalendar cal) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\iCalParser.cs:line 207
       at Ical.Net.Serialization.iCalendar.iCalParser.icalendar(ISerializationContext ctx) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\iCalParser.cs:line 144
       at Ical.Net.Serialization.iCalendar.Serializers.CalendarSerializer.Deserialize(TextReader tr) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\Serializers\CalendarSerializer.cs:line 66
       at Ical.Net.Serialization.iCalendar.Serializers.SerializerBase.Deserialize(Stream stream, Encoding encoding) in C:\dev\ical.net\ical.NET\Serialization\iCalendar\Serializers\SerializerBase.cs:line 39
       at Ical.Net.Calendar.LoadFromStream(Stream s, Encoding e, ISerializer serializer) in C:\dev\ical.net\ical.NET\Calendar.cs:line 113
       at Ical.Net.Calendar.LoadFromStream(TextReader tr, ISerializer serializer) in C:\dev\ical.net\ical.NET\Calendar.cs:line 137
       at Ical.Net.Calendar.LoadFromStream(TextReader tr) in C:\dev\ical.net\ical.NET\Calendar.cs:line 118

**Comment by aluxnimm** [comment] 2016-09-29 14:30
Looks similar to #102

**Comment by rianjs** [comment] 2016-10-03 14:36
I'm going to close this as a duplicate of #102 (thanks @aluxnimm ). @SanderSchutten, if you disagree, please feel free to re-open.

**Closed as completed by rianjs** 2016-10-03 14:36 UTC
