### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by manojmore** [ical-org/ical.net#194] opened 2016-12-01 14:26 UTC
Using Ical.net version 2.1.0.14533

I am trying to fetch events from google calendar.

Specific Issue while retrieving Google Calendar which have event with exception with only description changed.

Steps to reproduce
i) create google calendar with recurrent events
ii) edit any event from this calendar, only change the description and not the times.
iii) Now try to use GetOccurences(startDate, endDate) to fetch occurrences for this calendar. It gives error {"**Collection was modified; enumeration operation may not execute**."}

**Comment by rianjs** [comment] 2016-12-01 14:39
Dupe of #148

**Closed as completed by rianjs** 2016-12-01 14:39 UTC

**Comment by manojmore** [comment] 2016-12-19 11:05
Thanks! version 2.2.25 has fixed this issue.

**Comment by rianjs** [comment] 2016-12-19 15:52
(I knew I had forgotten to post the message that I had fixed it in some thread, but I couldn't find it... Glad you found it independently.)
