### ISSUE TITLE
Supporting WinRT platform

### ISSUE THREAD

**Issue by ghost** [ical-org/ical.net#88] opened 2016-08-04 11:52 UTC
I need this library for WinRT platform. I created separate project and moved your code to this project. I moved tests too. So now I have working library for WinRT.

I can put it on github as different library. But I'm afraid that nobody'll improve this library in the future.
Do you need this code? Can you implement it to your project?

**Comment by rianjs** [comment] 2016-08-12 10:49
It sounds like you have some private changes that you made to add WinRT support. Assuming they're safe, I'm open to merging them directly into ical.net, and publishing a new nuget package.

As you said, you shouldn't maintain a private version for WinRT, because it won't get any of the features and performance enhancements that are added to ical.net, so I would suggest you avoid your current solution.

Do you know how to contribute changes to open source projects? Here's a high-level overview of how to propose a code change to ical.net:
1. Fork the library
2. Clone your fork to your computer
3. Create a new branch `git checkout -b AddWinRtSupport`
4. Make the smallest number of changes that are required to add the WinRT support, making sure the unit tests pass
5. Commit the changes `git commit -m"Add WinRT support #88"`
6. Push them to a new branch of your fork `git push origin AddWinRtSupport`
7. Open a pull request asking to merge your branch `AddWinRtSupport` to `rianjs/ical.net/master` (or whatever the exact name my "master" branch is -- I'm writing this offline at the moment)

If you're not comfortable doing this, you can wait a little bit. .NET Core support should fill the gap for WinRT: #23

**Comment by rianjs** [comment] 2016-08-17 19:19
@Pizhon - I'm going to close this as a duplicate of #23. If you have a mergeable intermediate step that works for WinRT but not all of .NET Core, feel free to re-open, and I'll have a look.

**Closed as completed by rianjs** 2016-08-17 19:19 UTC
